apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    name: letsencrypt-unqork
  spec:
    acme:
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      email: unqork@unqork.com
      privateKeySecretRef:
        name: letsencrypt-unqork
      solvers:
        - http01:
          ingress:
            class: nginx