apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: hello-unqork
   annotations:
     kubernetes.io/ingress.class: nginx
     cert-manager.io/issuer: "letsencrypt-unqork"
 spec:
   tls:
     - hosts:
       - demo.unqork.com
       secretName: hello-secret-tls
   rules:
   - host: demo.unqork.com
     http:
       paths:
       - path: /
         backend:
           serviceName: hello-unqork
           servicePort: 8080