#! /usr/bin/env python3

def overlap(A, B):
    return (A[0] <= B[2]) and (B[0] <= A[2]) and (A[1] >= B[3]) and (B[1] >= A[3])

def main():
    line = input().strip()
    coord = list(map(int, line.split(',')))
    A = coord[:4]
    B = coord[4:]
    if overlap(A, B):
        print("True")
    else:
        print("False")

if __name__ == '__main__':
    main()