name: Create Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20
    - name: Build
      run: go build -o dictionary
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dictionary
        path: ./dictionary
